### ISSUE TITLE
[Feature Request] Ability to choose specific resolution

### ISSUE THREAD

**Issue by hyuri** [NickvisionApps/TubeConverter#100]
Hi!

It would be great to be able to choose a specific resolution. Or at least have an indication, like "Best (4K)", "Good (1080p)" etc.

I often want to download the video in a specific resolution but I never know which resolution the words "Best", "Good", etc. refer to on any given video. Sometimes the highest resolution available for a video is 1080p, sometimes it is 4K but, for most of my use I almost never want to download the 4K version — or any higher than 1080p, actually.

**Comment by fsobolev** [comment]
@nlogozzo It is possible to get list of available resolutions from metadata, to avoid using static list with, for example, 4k resolution where the video actually is 720p at max.
And for audio files we can leave "Best" and "Worst" ("Good" is not needed, it's already an alias for "Best" when downloading audio).

**Comment by fsobolev** [comment]
I think we can simply have a full list of available resolution (except resolutions < 360p). Because in your plan you can't let the user choose whether to download 1080p, 720p (only one of them would be "Good") or 360p when the maximum resolution is 4k. Also it's absolutely not obvious what are actual resolutions.
I think the list of resolutions should not be considered as technical information, because most if not all video hosting services shows it like this, so a user is aware of what does it mean and "more human" terms are not required here.

**Comment by nlogozzo** [comment]
Ok so switch the `Quality` field with a `Resolution` field and allow the user to simply pick the resolution they want to download.

**Comment by hyuri** [comment]
Nice! Switching from `Quality` to `Resolution` seems like the simplest solution.

In case you prefer to keep the Quality and "Best" | "Good" | "Worst" wording, maybe one of these could work:
1. "Best (4K) | Good (1080p) | Good (720p) | Worst (480p)"
2. "Best (4K) | Good (1080p) | Ok (720p) | Worst (480p)"

**Comment by nlogozzo** [comment]
At that point, listing Best, Good, Ok, Worst, we might as well list the resolutions and let the user pick that :)

**Comment by hyuri** [comment]
Perfect! :)

**Comment by DaPigGuy** [comment]
Should Audio Quality options remain as `Best/Good/Ok/Worst`?

**Comment by fsobolev** [comment]
> Should Audio Quality options remain as Best, Good, and Worst?

Best and Worst, Good was an alias for Best

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.5.0-rc2
