### ISSUE TITLE
Remember "Crop Thumbnail" setting

### ISSUE THREAD

**Issue by Batwam** [NickvisionApps/TubeConverter#342]
Hello, would it be possible for TuberConverter to remember the "Crop Thumbnail" setting, ideally based on the extension used? as per the subtitle description for this Switch, the thumbnail crop is mostly useful for music so it would make sense to do that, or set it to enabled by default for sound filetypes like flac/wav/mp3/... (or mayb both, set to true by default for music files but remember when changed)

**Comment by nlogozzo** [comment]
@fsobolev How do you think we should implement this? We can either remember the `Crop Thumbnail` setting per extension, like @Batwam suggested. But the problem I have with this is that `Crop Thumbnail` is an `Advanced Option` and I don't want people to forget that they have this turned on since, compared to `Number Video Titles` and `Resolution` that are saved, this option isn't visible on the main screen.

What I was thinking is maybe to have an option in Preferences under the `Converter` section, probably even expanded under `Embed Metadata`, called `Automatically crop audio thumbnails as square` (off by default), that if on, will turn `Crop Thumbnail` on if an audio extension is selected.

**Comment by fsobolev** [comment]
I think ideally there shouldn't be a separate advanced options page, but without it either the dialog would have too much height, or we would have to use wider dialog and lose adaptiveness. So I think this:

> What I was thinking is maybe to have an option in Preferences under the Converter section, probably even expanded under Embed Metadata, called Automatically crop audio thumbnails as square (off by default), that if on, will turn Crop Thumbnail on if an audio extension is selected.

is the best option.

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/05565ca0-d373-4905-a34a-5b62406b2285)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-rc1
