### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by garthmiller** [NickvisionApps/TubeConverter#389]
I installed Tube Converter on Ubuntu 20.04.6 LTS. No problem installing or running. But after it processes a download it doesn't save it. Just says there is an error.  I notice that when I try to select a save folder it always says "Error opening directory : Permission denied".

How can I give the app permission to save files somewhere?

**Comment by nlogozzo** [comment]
How did you install Tube Converter? Flatpak or snap?

**Comment by garthmiller** [comment]
After I stopped and started it a few times it began successfully saving files. I'm not sure what changed, but now it works.

**Comment by garthmiller** [comment]
I used the snap to install it.

**Comment by nlogozzo** [comment]
@soumyaDghosh handles the snap package...any idea?

**Comment by soumyaDghosh** [comment]
I actually removed the `home` plug and let the portal work. But, seems like, either it's not working, or the Ubuntu 20.04.6 doesn't have portals. In that case it should also not work with flatpak. But, if not, then kindly try with selecting a folder. And if you can share us a screenshot while you're in the Home folder while selecting a folder, that'll be a big help.

**Comment by soumyaDghosh** [comment]
Confirmed, what he said is a problem. But, I think it's more of a code problem, I guess. At a complete new install, the flatpak version shows `Save Folder[invalid]` which makes the user choose a folder manually for the first time. But, the snap auto chooses the `$HOME/Videos` folder, and that too with its raw location, instead of a portal based location. So, if a user doesn't choose a folder and keep it as it is. It'll fail.

**Comment by nlogozzo** [comment]
> At a complete new install, the flatpak version shows Save Folder[invalid] which makes the user choose a folder manually for the first time. But, the snap auto chooses the $HOME/Videos folder, and that too with its raw location, instead of a portal based location. So, if a user doesn't choose a folder and keep it as it is. It'll fail.

I can change this too:
```csharp
 _saveFolderString = g_get_user_special_dir(2); //XDG_DOWNLOAD_DIR
```

Which will choose the `xdg-download` dir at a complete new install in flatpak. Of course, this requires permissions to the `xdg-download` folder.

**Comment by soumyaDghosh** [comment]
> I can change this too:
> 
> ```cs
>  _saveFolderString = g_get_user_special_dir(2); //XDG_DOWNLOAD_DIR
> ```

Why is the snap also not showing invalid just like the flatpak

**Comment by nlogozzo** [comment]
> Why is the snap also not showing invalid just like the flatpak

In `Shared/Configuration.cs` we had:
```csharp
PreviousSaveFolder = Environment.GetFolderPath(Environment.SpecialFolder.MyVideos);
```

Which in `snap` would return `$HOME/Videos` and on `flatpak` would return `""` since it doesn't have permission. So I removed this all together and instead in `AddDownloadDialog` if `PreviousSaveFolder` is empty (which it will be on first run) it will choose the portal location provided by `g_get_user_special_dir` instead.

**Comment by garthmiller** [comment]
I installed using the snap. It started working after I restarted a couple
of times.

Thanks

**Comment by nlogozzo** [comment]
@garthmiller Was this the first download you ran using the app? Did you select a `Save Folder` or used the default one provided?

As @soumyaDghosh said, selecting a `Save Folder` should fix your issue if that's the case.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.2-rc1
